name: Lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version: 'stable'
      - uses: golangci/golangci-lint-action@v6
      - id: govulncheck
        uses: golang/govulncheck-action@v1
